name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.409
    - name: Restore dependencies
      run: cd helloworld-csharp && dotnet restore
    - name: Build
      run: cd helloworld-csharp && dotnet build --no-restore
    - name: Test
      run: cd helloworld-csharp && dotnet test --no-build --verbosity normal
